#
# Makefile
#
# Autor: H.Drachenfels
# erstellt am: 24.6.2011
#

CXX = g++
CPPFLAGS =
CXXFLAGS = -g -W -Wall -ansi -pedantic

TARGET = datetest

OBJECTS = date.o

all: $(TARGET)

clean:
	rm -f $(TARGET) $(TARGET).o $(OBJECTS)

$(TARGET): $(TARGET).o $(OBJECTS)
	$(CXX) $(CXXFLAGS) $^ -o $@

datetest.o: datetest.cpp date.h
date.o: date.cpp date.h

